server:
  port: 8899
 # 运行端口
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#Json序列化配置 默认格式   yyyy-MM-dd HH:mm:ss  东八区
  datasource:
    url: jdbc:mysql://10.0.0.111:3306/salesupportmllcp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: jiuchen
    password: jiuchen0711A602%
#    driver-class-name: com.mysql.jdbc.Driver